/**
 * Building footprints and synthetic parcels for the six-house Oakhurst scene (?scene=six).
 *
 * GENERATED by `node scripts/fetch-footprints.mjs` on 2026-09-12.
 * Do not hand-edit: re-run the script.
 *
 * ---------------------------------------------------------------------------
 * Building footprints (`building.footprint`, `building.source === 'osm'`)
 * are derived from OpenStreetMap data, © OpenStreetMap contributors, available
 * under the Open Database License (ODbL) v1.0:
 *   https://www.openstreetmap.org/copyright
 *   https://opendatacommons.org/licenses/odbl/1-0/
 * Any public use of this data must carry that attribution and share alike.
 *
 * The footprints are the ONLY surveyed geometry here. Nothing in this file is
 * derived from Google's photorealistic 3D tiles — that tileset is licensed
 * imagery, not a data source, and vectorising it would be a terms violation as
 * well as unredistributable.
 *
 * `parcel` is NOT a real lot line. There is no free parcel polygon for DeKalb
 * or Fulton, so each one is synthesised from the footprint's oriented bounding
 * box pushed out 9 m at the sides and 18 m front and back, capped at
 * 0.35 acres (see `parcel.js`). It marks roughly where a lot would be. It
 * is not a survey and must never be presented as one.
 *
 * 6 of 6 rows resolved to a footprint.
 * ---------------------------------------------------------------------------
 */

export const SIX_HOUSE_GEOMETRY = Object.freeze({
  'DEMO-SIX-001': Object.freeze({
    id: 'DEMO-SIX-001',
    centroid: Object.freeze({ lat: 33.7584443, lng: -84.3074507 }),
    shiftM: 19.25,
    building: Object.freeze({
      source: 'osm',
      osmId: 'way/51282597',
      buildingTag: 'yes',
      distanceFromAuthoredM: 19.3,
      areaM2: 192.1,
      footprint: Object.freeze([
        Object.freeze([
          [-84.3074124, 33.7585337],
          [-84.307412, 33.7585051],
          [-84.307388, 33.7585054],
          [-84.3073865, 33.7584024],
          [-84.3073986, 33.7584023],
          [-84.3073982, 33.7583728],
          [-84.3074576, 33.7583722],
          [-84.3074573, 33.7583542],
          [-84.307493, 33.7583539],
          [-84.3074932, 33.7583652],
          [-84.3075249, 33.7583649],
          [-84.3075255, 33.7584055],
          [-84.3074977, 33.7584058],
          [-84.3074994, 33.7585328],
        ]),
      ]),
    }),
    parcel: Object.freeze({
      source: 'synthetic',
      areaM2: 1416.4,
      areaAcres: 0.35,
      headingDeg: 359.3,
      setbackScale: 0.793,
      ring: Object.freeze([
        [-84.3076825, 33.7585951],
        [-84.307678, 33.7582879],
        [-84.3072306, 33.7582924],
        [-84.3072351, 33.7585996],
      ]),
    }),
  }),
  'DEMO-SIX-002': Object.freeze({
    id: 'DEMO-SIX-002',
    centroid: Object.freeze({ lat: 33.7579907, lng: -84.3044212 }),
    shiftM: 0.04,
    building: Object.freeze({
      source: 'osm',
      osmId: 'way/51309531',
      buildingTag: 'yes',
      distanceFromAuthoredM: 0,
      areaM2: 178.1,
      footprint: Object.freeze([
        Object.freeze([
          [-84.3043758, 33.7579171],
          [-84.3044841, 33.757916],
          [-84.3044859, 33.7580541],
          [-84.3043412, 33.7580555],
          [-84.3043403, 33.7579915],
          [-84.3043768, 33.7579911],
        ]),
      ]),
    }),
    parcel: Object.freeze({
      source: 'synthetic',
      areaM2: 1416.4,
      areaAcres: 0.35,
      headingDeg: 179.3,
      setbackScale: 0.885,
      ring: Object.freeze([
        [-84.3046551, 33.7578428],
        [-84.3046591, 33.758124],
        [-84.3041701, 33.7581287],
        [-84.3041662, 33.7578475],
      ]),
    }),
  }),
  'DEMO-SIX-003': Object.freeze({
    id: 'DEMO-SIX-003',
    centroid: Object.freeze({ lat: 33.7573824, lng: -84.3080082 }),
    shiftM: 0.05,
    building: Object.freeze({
      source: 'osm',
      osmId: 'way/51304082',
      buildingTag: 'detached',
      distanceFromAuthoredM: 0,
      areaM2: 154.7,
      footprint: Object.freeze([
        Object.freeze([
          [-84.3079363, 33.7574269],
          [-84.3079362, 33.7574175],
          [-84.3079093, 33.7574176],
          [-84.3079092, 33.7573857],
          [-84.3079367, 33.7573856],
          [-84.3079365, 33.7573349],
          [-84.3080853, 33.7573343],
          [-84.3080855, 33.7573738],
          [-84.3080937, 33.7573738],
          [-84.308094, 33.7574263],
        ]),
      ]),
    }),
    parcel: Object.freeze({
      source: 'synthetic',
      areaM2: 1416.4,
      areaAcres: 0.35,
      headingDeg: 269.7,
      setbackScale: 0.898,
      ring: Object.freeze([
        [-84.3081801, 33.7571887],
        [-84.3078207, 33.75719],
        [-84.3078228, 33.7575726],
        [-84.3081822, 33.7575712],
      ]),
    }),
  }),
  'DEMO-SIX-004': Object.freeze({
    id: 'DEMO-SIX-004',
    centroid: Object.freeze({ lat: 33.7565253, lng: -84.3052188 }),
    shiftM: 0.04,
    building: Object.freeze({
      source: 'osm',
      osmId: 'way/51282519',
      buildingTag: 'yes',
      distanceFromAuthoredM: 0,
      areaM2: 239.7,
      footprint: Object.freeze([
        Object.freeze([
          [-84.3050858, 33.7564888],
          [-84.3051564, 33.7564207],
          [-84.3053517, 33.7565617],
          [-84.3052811, 33.7566299],
        ]),
      ]),
    }),
    parcel: Object.freeze({
      source: 'synthetic',
      areaM2: 1416.4,
      areaAcres: 0.35,
      headingDeg: 131,
      setbackScale: 0.764,
      ring: Object.freeze([
        [-84.3049319, 33.7565414],
        [-84.3052398, 33.7567637],
        [-84.3055056, 33.7565092],
        [-84.3051977, 33.7562869],
      ]),
    }),
  }),
  'DEMO-SIX-005': Object.freeze({
    id: 'DEMO-SIX-005',
    centroid: Object.freeze({ lat: 33.7556043, lng: -84.3074345 }),
    shiftM: 0.06,
    building: Object.freeze({
      source: 'osm',
      osmId: 'way/51298558',
      buildingTag: 'yes',
      distanceFromAuthoredM: 0.1,
      areaM2: 154.1,
      footprint: Object.freeze([
        Object.freeze([
          [-84.3074131, 33.7556709],
          [-84.3074131, 33.7556556],
          [-84.3073692, 33.7556556],
          [-84.307369, 33.7555597],
          [-84.3074079, 33.7555597],
          [-84.3074079, 33.7555345],
          [-84.3074847, 33.7555344],
          [-84.3074847, 33.7555612],
          [-84.3074923, 33.7555612],
          [-84.3074924, 33.7556708],
        ]),
      ]),
    }),
    parcel: Object.freeze({
      source: 'synthetic',
      areaM2: 1416.4,
      areaAcres: 0.35,
      headingDeg: 179.9,
      setbackScale: 0.921,
      ring: Object.freeze([
        [-84.3076713, 33.7554597],
        [-84.3076718, 33.7557451],
        [-84.3071901, 33.7557457],
        [-84.3071896, 33.7554603],
      ]),
    }),
  }),
  'DEMO-SIX-006': Object.freeze({
    id: 'DEMO-SIX-006',
    centroid: Object.freeze({ lat: 33.7578759, lng: -84.3062833 }),
    shiftM: 0.03,
    building: Object.freeze({
      source: 'osm',
      osmId: 'way/51294917',
      buildingTag: 'yes',
      distanceFromAuthoredM: 0,
      areaM2: 175.6,
      footprint: Object.freeze([
        Object.freeze([
          [-84.3062275, 33.7579257],
          [-84.3062293, 33.7577969],
          [-84.306338, 33.7577979],
          [-84.3063357, 33.757958],
          [-84.3062668, 33.7579573],
          [-84.306267, 33.7579484],
          [-84.3062272, 33.757948],
        ]),
      ]),
    }),
    parcel: Object.freeze({
      source: 'synthetic',
      areaM2: 1416.4,
      areaAcres: 0.35,
      headingDeg: 180.7,
      setbackScale: 0.886,
      ring: Object.freeze([
        [-84.3060581, 33.7577235],
        [-84.3060537, 33.7580268],
        [-84.3065069, 33.7580313],
        [-84.3065113, 33.757728],
      ]),
    }),
  }),
});

/** @returns {object|null} geometry record for a property id */
export function sixHouseGeometryFor(id) {
  return SIX_HOUSE_GEOMETRY[String(id || '').trim()] || null;
}

/** @returns {Array<Array<number>>|null} outer [lon,lat] ring of the building */
export function sixHouseFootprintRing(id) {
  return sixHouseGeometryFor(id)?.building?.footprint?.[0] || null;
}

/** @returns {Array<Array<number>>|null} the synthetic parcel ring */
export function sixHouseParcelRing(id) {
  return sixHouseGeometryFor(id)?.parcel?.ring || null;
}

/** Rows whose footprint lookup found nothing — these degrade to a parcel glow. */
export const SIX_HOUSE_ROWS_WITHOUT_FOOTPRINT = Object.freeze([

]);
