/**
 * Building footprints and county parcels for the six-house Oakhurst scene (?scene=six).
 *
 * GENERATED by `node scripts/fetch-footprints.mjs` on 2026-09-13.
 * Do not hand-edit: re-run the script.
 *
 * ---------------------------------------------------------------------------
 * Building footprints (`building.footprint`, `building.source === 'osm'`)
 * are derived from OpenStreetMap data, © OpenStreetMap contributors, available
 * under the Open Database License (ODbL) v1.0:
 *   https://www.openstreetmap.org/copyright
 *   https://opendatacommons.org/licenses/odbl/1-0/
 * Any public use of this data must carry that attribution and share alike.
 *
 * The footprints are the ONLY surveyed geometry here. Nothing in this file is
 * derived from Google's photorealistic 3D tiles — that tileset is licensed
 * imagery, not a data source, and vectorising it would be a terms violation as
 * well as unredistributable.
 *
 * `parcel` is a REAL county lot line wherever `parcel.source` is
 * `'dekalb-gis'` or `'fulton-gis'`. Those rings come from the counties' public
 * ArcGIS REST parcel layers, fetched by `node scripts/fetch-parcels.mjs` on
 * 2026-09-13, and each block carries its own `attribution`:
 *
 *   DeKalb County GIS Department
 *   Fulton County GIS (Property Map Viewer)
 *
 * ONLY the ring, the public parcel identifier and the area are kept. Those
 * layers are cadastral and also serve the current owner's name and mailing
 * address; the rows in this repository are invented and every signal on them is
 * fiction, so no owner identity is stored here and none ever should be.
 *
 * A row whose `parcel.source` is still `'synthetic'` has NO county polygon —
 * that block is the old oriented-bounding-box guess, it is kept only as data,
 * and the near-field layer refuses to draw it. Such a row renders its building
 * outline and nothing else.
 *
 * 6 of 6 rows carry a surveyed county parcel.
 * ---------------------------------------------------------------------------
 */

export const SIX_HOUSE_GEOMETRY = Object.freeze({
  'DEMO-SIX-001': Object.freeze({
    id: 'DEMO-SIX-001',
    centroid: Object.freeze({ lat: 33.7584443, lng: -84.3074507 }),
    shiftM: 19.25,
    building: Object.freeze({
      source: 'osm',
      osmId: 'way/51282597',
      buildingTag: 'yes',
      distanceFromAuthoredM: 19.3,
      areaM2: 192.1,
      footprint: Object.freeze([
        Object.freeze([
          [-84.3074124, 33.7585337],
          [-84.307412, 33.7585051],
          [-84.307388, 33.7585054],
          [-84.3073865, 33.7584024],
          [-84.3073986, 33.7584023],
          [-84.3073982, 33.7583728],
          [-84.3074576, 33.7583722],
          [-84.3074573, 33.7583542],
          [-84.307493, 33.7583539],
          [-84.3074932, 33.7583652],
          [-84.3075249, 33.7583649],
          [-84.3075255, 33.7584055],
          [-84.3074977, 33.7584058],
          [-84.3074994, 33.7585328],
        ]),
      ]),
    }),
    parcel: Object.freeze({
      source: 'dekalb-gis',
      attribution: "DeKalb County GIS Department",
      parcelId: '15 213 03 097',
      // The county's own address for this lot. Stored so the fictional-address
      // rule can be CHECKED (src/investor/mock/siteAddress.js); it is never the
      // address the row shows and nothing renders it.
      siteAddress: "247 Maxwell Street Decatur, GA 30030",
      areaM2: 1430.8,
      areaAcres: 0.3535,
      ring: Object.freeze([
        [-84.3073409, 33.7589303],
        [-84.3073465, 33.7582515],
        [-84.3075439, 33.7582495],
        [-84.3075402, 33.7587045],
        [-84.3075388, 33.7588694],
        [-84.3075381, 33.7589531],
        [-84.3073407, 33.758955],
      ]),
    }),
    street: Object.freeze({
      source: 'osm',
      osmId: 'way/9184692',
      name: "Maxwell Street",
      highway: 'residential',
      bearingDeg: 179.5,
      distanceM: 26.5,
    }),
  }),
  'DEMO-SIX-002': Object.freeze({
    id: 'DEMO-SIX-002',
    centroid: Object.freeze({ lat: 33.7579907, lng: -84.3044212 }),
    shiftM: 0.04,
    building: Object.freeze({
      source: 'osm',
      osmId: 'way/51309531',
      buildingTag: 'yes',
      distanceFromAuthoredM: 0,
      areaM2: 178.1,
      footprint: Object.freeze([
        Object.freeze([
          [-84.3043758, 33.7579171],
          [-84.3044841, 33.757916],
          [-84.3044859, 33.7580541],
          [-84.3043412, 33.7580555],
          [-84.3043403, 33.7579915],
          [-84.3043768, 33.7579911],
        ]),
      ]),
    }),
    parcel: Object.freeze({
      source: 'dekalb-gis',
      attribution: "DeKalb County GIS Department",
      parcelId: '15 213 03 207',
      // The county's own address for this lot. Stored so the fictional-address
      // rule can be CHECKED (src/investor/mock/siteAddress.js); it is never the
      // address the row shows and nothing renders it.
      siteAddress: "120 Maxwell Street Decatur, GA 30030",
      areaM2: 1152.9,
      areaAcres: 0.2849,
      ring: Object.freeze([
        [-84.3043387, 33.7575253],
        [-84.3045197, 33.7575235],
        [-84.3045284, 33.7581418],
        [-84.3043475, 33.7581436],
      ]),
    }),
    street: Object.freeze({
      source: 'osm',
      osmId: 'way/9184692',
      name: "Maxwell Street",
      highway: 'residential',
      bearingDeg: 359.6,
      distanceM: 26.1,
    }),
  }),
  'DEMO-SIX-003': Object.freeze({
    id: 'DEMO-SIX-003',
    centroid: Object.freeze({ lat: 33.7573824, lng: -84.3080082 }),
    shiftM: 0.05,
    building: Object.freeze({
      source: 'osm',
      osmId: 'way/51304082',
      buildingTag: 'detached',
      distanceFromAuthoredM: 0,
      areaM2: 154.7,
      footprint: Object.freeze([
        Object.freeze([
          [-84.3079363, 33.7574269],
          [-84.3079362, 33.7574175],
          [-84.3079093, 33.7574176],
          [-84.3079092, 33.7573857],
          [-84.3079367, 33.7573856],
          [-84.3079365, 33.7573349],
          [-84.3080853, 33.7573343],
          [-84.3080855, 33.7573738],
          [-84.3080937, 33.7573738],
          [-84.308094, 33.7574263],
        ]),
      ]),
    }),
    parcel: Object.freeze({
      source: 'dekalb-gis',
      attribution: "DeKalb County GIS Department",
      parcelId: '15 213 03 234',
      // The county's own address for this lot. Stored so the fictional-address
      // rule can be CHECKED (src/investor/mock/siteAddress.js); it is never the
      // address the row shows and nothing renders it.
      siteAddress: "602 3rd Avenue Decatur, GA 30030",
      areaM2: 749,
      areaAcres: 0.1851,
      ring: Object.freeze([
        [-84.307628, 33.7573005],
        [-84.3081568, 33.7572953],
        [-84.3081571, 33.7573472],
        [-84.3081587, 33.7574327],
        [-84.307629, 33.7574379],
      ]),
    }),
    street: Object.freeze({
      source: 'osm',
      osmId: 'way/9187948',
      name: "3rd Avenue",
      highway: 'residential',
      bearingDeg: 269.5,
      distanceM: 22.6,
    }),
  }),
  'DEMO-SIX-004': Object.freeze({
    id: 'DEMO-SIX-004',
    centroid: Object.freeze({ lat: 33.7563179, lng: -84.3056498 }),
    shiftM: 46.06,
    building: Object.freeze({
      source: 'osm',
      osmId: 'way/51277800',
      buildingTag: 'yes',
      distanceFromAuthoredM: 46.1,
      areaM2: 141.8,
      footprint: Object.freeze([
        Object.freeze([
          [-84.3056032, 33.7562573],
          [-84.3056616, 33.7562348],
          [-84.3057292, 33.7563569],
          [-84.3056298, 33.7563953],
          [-84.305573, 33.7562926],
          [-84.305614, 33.7562768],
        ]),
      ]),
    }),
    parcel: Object.freeze({
      source: 'dekalb-gis',
      attribution: "DeKalb County GIS Department",
      parcelId: '15 213 03 250',
      // The county's own address for this lot. Stored so the fictional-address
      // rule can be CHECKED (src/investor/mock/siteAddress.js); it is never the
      // address the row shows and nothing renders it.
      siteAddress: "1305 Oakview Road Decatur, GA 30030",
      areaM2: 1106.1,
      areaAcres: 0.2733,
      ring: Object.freeze([
        [-84.3054727, 33.7562253],
        [-84.3054917, 33.7562181],
        [-84.305503, 33.7562138],
        [-84.3056587, 33.756155],
        [-84.3059495, 33.7566622],
        [-84.3057878, 33.7567236],
      ]),
    }),
    street: Object.freeze({
      source: 'osm',
      osmId: 'way/85363014',
      name: "Oakview Road",
      highway: 'residential',
      bearingDeg: 155.9,
      distanceM: 22.4,
    }),
  }),
  'DEMO-SIX-005': Object.freeze({
    id: 'DEMO-SIX-005',
    centroid: Object.freeze({ lat: 33.7556043, lng: -84.3074345 }),
    shiftM: 0.06,
    building: Object.freeze({
      source: 'osm',
      osmId: 'way/51298558',
      buildingTag: 'yes',
      distanceFromAuthoredM: 0.1,
      areaM2: 154.1,
      footprint: Object.freeze([
        Object.freeze([
          [-84.3074131, 33.7556709],
          [-84.3074131, 33.7556556],
          [-84.3073692, 33.7556556],
          [-84.307369, 33.7555597],
          [-84.3074079, 33.7555597],
          [-84.3074079, 33.7555345],
          [-84.3074847, 33.7555344],
          [-84.3074847, 33.7555612],
          [-84.3074923, 33.7555612],
          [-84.3074924, 33.7556708],
        ]),
      ]),
    }),
    parcel: Object.freeze({
      source: 'dekalb-gis',
      attribution: "DeKalb County GIS Department",
      parcelId: '15 213 03 219',
      // The county's own address for this lot. Stored so the fictional-address
      // rule can be CHECKED (src/investor/mock/siteAddress.js); it is never the
      // address the row shows and nothing renders it.
      siteAddress: "1421 Oakview Road Decatur, GA 30030",
      areaM2: 728.2,
      areaAcres: 0.18,
      ring: Object.freeze([
        [-84.3073485, 33.7555026],
        [-84.3075114, 33.7554369],
        [-84.3075154, 33.7558312],
        [-84.307516, 33.7558999],
        [-84.3073515, 33.7559015],
      ]),
    }),
    street: Object.freeze({
      source: 'osm',
      osmId: 'way/85363014',
      name: "Oakview Road",
      highway: 'residential',
      bearingDeg: 154.6,
      distanceM: 19.7,
    }),
  }),
  'DEMO-SIX-006': Object.freeze({
    id: 'DEMO-SIX-006',
    centroid: Object.freeze({ lat: 33.7578759, lng: -84.3062833 }),
    shiftM: 0.03,
    building: Object.freeze({
      source: 'osm',
      osmId: 'way/51294917',
      buildingTag: 'yes',
      distanceFromAuthoredM: 0,
      areaM2: 175.6,
      footprint: Object.freeze([
        Object.freeze([
          [-84.3062275, 33.7579257],
          [-84.3062293, 33.7577969],
          [-84.306338, 33.7577979],
          [-84.3063357, 33.757958],
          [-84.3062668, 33.7579573],
          [-84.306267, 33.7579484],
          [-84.3062272, 33.757948],
        ]),
      ]),
    }),
    parcel: Object.freeze({
      source: 'dekalb-gis',
      attribution: "DeKalb County GIS Department",
      parcelId: '15 213 03 196',
      // The county's own address for this lot. Stored so the fictional-address
      // rule can be CHECKED (src/investor/mock/siteAddress.js); it is never the
      // address the row shows and nothing renders it.
      siteAddress: "216 Maxwell Street Decatur, GA 30030",
      areaM2: 1048.1,
      areaAcres: 0.259,
      ring: Object.freeze([
        [-84.3061854, 33.7575071],
        [-84.3063499, 33.7575055],
        [-84.3063586, 33.7581238],
        [-84.3061941, 33.7581254],
      ]),
    }),
    street: Object.freeze({
      source: 'osm',
      osmId: 'way/9184692',
      name: "Maxwell Street",
      highway: 'residential',
      bearingDeg: 359.6,
      distanceM: 37.6,
    }),
  }),
});

/** @returns {object|null} geometry record for a property id */
export function sixHouseGeometryFor(id) {
  return SIX_HOUSE_GEOMETRY[String(id || '').trim()] || null;
}

/** @returns {Array<Array<number>>|null} outer [lon,lat] ring of the building */
export function sixHouseFootprintRing(id) {
  return sixHouseGeometryFor(id)?.building?.footprint?.[0] || null;
}

/** @returns {Array<Array<number>>|null} the synthetic parcel ring */
export function sixHouseParcelRing(id) {
  return sixHouseGeometryFor(id)?.parcel?.ring || null;
}

/** Rows whose footprint lookup found nothing — these degrade to a parcel glow. */
export const SIX_HOUSE_ROWS_WITHOUT_FOOTPRINT = Object.freeze([

]);
