/**
 * The Drive Mode v1 route: one road-following loop past all six DEMO-SIX houses.
 *
 * GENERATED by `node scripts/fetch-route.mjs` on 2026-09-13.
 * Do not hand-edit: re-run the script.
 *
 * ---------------------------------------------------------------------------
 * The road geometry is derived from OpenStreetMap data, © OpenStreetMap
 * contributors, available under the Open Database License (ODbL) v1.0:
 *   https://www.openstreetmap.org/copyright
 *   https://opendatacommons.org/licenses/odbl/1-0/
 * Any public use of this data must carry that attribution and share alike.
 *
 * The visiting order and the road-following geometry were solved once by the
 * public OSRM demo server (router.project-osrm.org), which routes on the same
 * OpenStreetMap data. **Nothing in the app calls a routing service at runtime.**
 *
 * Waypoints are the street-facing side of each house — the point on the nearest
 * residential way that the footprint faces — not the roofs, so the loop passes
 * the front of every property rather than routing to the middle of a building.
 *
 * Every vertex below was checked against OSM's own highway geometry and sits
 * within 8 m of a mapped road (worst: 0.07 m). The route never
 * cuts across a yard.
 * ---------------------------------------------------------------------------
 */

/** Closed loop of [lon, lat] vertices, in travel order. */
export const SIX_ROUTE = Object.freeze([
  [-84.307448, 33.758206],
  [-84.30705, 33.758209],
  [-84.306286, 33.758214],
  [-84.304423, 33.758225],
  [-84.304248, 33.758226],
  [-84.303863, 33.758228],
  [-84.303722, 33.758229],
  [-84.303669, 33.75823],
  [-84.303848, 33.757503],
  [-84.303875, 33.757387],
  [-84.30391, 33.757281],
  [-84.303964, 33.757155],
  [-84.304037, 33.757025],
  [-84.304142, 33.756898],
  [-84.304271, 33.756767],
  [-84.304389, 33.75666],
  [-84.304532, 33.75656],
  [-84.304708, 33.756464],
  [-84.304865, 33.75639],
  [-84.305353, 33.756208],
  [-84.30547, 33.756164],
  [-84.305551, 33.756134],
  [-84.306094, 33.755932],
  [-84.306288, 33.75586],
  [-84.306737, 33.755685],
  [-84.306807, 33.755658],
  [-84.306966, 33.755593],
  [-84.307343, 33.755444],
  [-84.307813, 33.755259],
  [-84.308168, 33.755106],
  [-84.308224, 33.755081],
  [-84.308226, 33.755134],
  [-84.30823, 33.755364],
  [-84.308246, 33.75685],
  [-84.308252, 33.757381],
  [-84.308261, 33.758201],
  [-84.308158, 33.758202],
  [-84.307448, 33.758206],
].map((point) => Object.freeze(point)));

/** Total length of the loop in metres, measured along the polyline. */
export const SIX_ROUTE_LENGTH_M = 1360.2;

/** What the routing engine estimated a car would take, in seconds. */
export const SIX_ROUTE_DRIVE_SECONDS = 206.3;

/** Worst distance from any vertex to a mapped road, in metres. */
export const SIX_ROUTE_MAX_OFF_ROAD_M = 0.07;

/** The houses the loop was built to pass, in the order it reaches them. */
export const SIX_ROUTE_HOUSES = Object.freeze([
  Object.freeze({ id: 'DEMO-SIX-006', street: "Maxwell Street", alongM: 107.5 }),
  Object.freeze({ id: 'DEMO-SIX-002', street: "Maxwell Street", alongM: 280 }),
  Object.freeze({ id: 'DEMO-SIX-004', street: "Oakview Road", alongM: 663.8 }),
  Object.freeze({ id: 'DEMO-SIX-005', street: "Oakview Road", alongM: 846.6 }),
  Object.freeze({ id: 'DEMO-SIX-003', street: "3rd Avenue", alongM: 1193.7 }),
  Object.freeze({ id: 'DEMO-SIX-001', street: "Maxwell Street", alongM: 1360.2 }),
]);

export const SIX_ROUTE_ATTRIBUTION = Object.freeze({
  data: '© OpenStreetMap contributors',
  licence: 'ODbL 1.0',
  url: 'https://www.openstreetmap.org/copyright',
  routing: 'OSRM demo server (router.project-osrm.org), one-time fetch',
});
